'use strict';

const HUB_NAME = 'react-native-debug-toolkit-hub';
const HUB_VERSION = '4.0.0';
const PROTOCOL_VERSION = 1;
const CANONICAL_VERSION = 1;
const DEFAULT_PORT = 3800;
const API_PREFIX = '/api/v1';

const STALE_TIMEOUT_MS = 45 * 1000;
const HEARTBEAT_INTERVAL_MS = 15 * 1000;
const MAX_EVENT_WIRE_BYTES = 60 * 1024;
const MAX_ENVELOPE_BYTES = 64 * 1024;
const MAX_BATCH_EVENTS = 50;
const MAX_BATCH_BYTES = 512 * 1024;
const MAX_BUFFER_EVENTS = 500;
const MAX_BUFFER_BYTES = 2 * 1024 * 1024;
const RETENTION_DAYS = 7;
const RETENTION_MS = RETENTION_DAYS * 24 * 60 * 60 * 1000;
const MAX_STORAGE_BYTES = 20_000_000_000;
const CONTEXT_MAX_EVENTS = 200;
const CONTEXT_MAX_BYTES = 128 * 1024;
const CONTEXT_DEFAULT_WINDOW_MS = 10 * 60 * 1000;
const CONTEXT_ERROR_LIMIT = 50;
const CONTEXT_ADJACENT = 3;

// Field limits
const SESSION_ID_LENGTH = 36;
const TYPE_PATTERN = /^[A-Za-z0-9._-]{1,64}$/;
const APP_ID_PATTERN = /^[A-Za-z0-9._-]{1,128}$/;
const PLATFORM_MAX_BYTES = 16;
const OS_VERSION_MAX_BYTES = 64;
const MANUFACTURER_MAX_BYTES = 64;
const MODEL_MAX_BYTES = 128;
const APP_VERSION_MAX_BYTES = 64;
const BUILD_NUMBER_MAX_BYTES = 64;
const NATIVE_APP_ID_MAX_BYTES = 200;
const DEVICE_ID_MAX_CHARS = 96;
const ENTRY_ID_MAX_CHARS = 53;

const SEVERITIES = ['debug', 'info', 'warn', 'error', 'fatal'];

module.exports = {
  HUB_NAME, HUB_VERSION, PROTOCOL_VERSION, CANONICAL_VERSION,
  DEFAULT_PORT, API_PREFIX,
  STALE_TIMEOUT_MS, HEARTBEAT_INTERVAL_MS,
  MAX_EVENT_WIRE_BYTES, MAX_ENVELOPE_BYTES, MAX_BATCH_EVENTS, MAX_BATCH_BYTES,
  MAX_BUFFER_EVENTS, MAX_BUFFER_BYTES,
  RETENTION_DAYS, RETENTION_MS, MAX_STORAGE_BYTES,
  CONTEXT_MAX_EVENTS, CONTEXT_MAX_BYTES, CONTEXT_DEFAULT_WINDOW_MS,
  CONTEXT_ERROR_LIMIT, CONTEXT_ADJACENT,
  SESSION_ID_LENGTH, TYPE_PATTERN, APP_ID_PATTERN,
  PLATFORM_MAX_BYTES, OS_VERSION_MAX_BYTES, MANUFACTURER_MAX_BYTES,
  MODEL_MAX_BYTES, APP_VERSION_MAX_BYTES, BUILD_NUMBER_MAX_BYTES,
  NATIVE_APP_ID_MAX_BYTES, DEVICE_ID_MAX_CHARS, ENTRY_ID_MAX_CHARS,
  SEVERITIES,
};
